feat: add custom font sizes to fields
documenso/documenso pull request #1376
Opened 2024-10-02 12:10 UTC by ephraimduncan

## Description

Add custom font sizes to fields

https://github.com/user-attachments/assets/1473a4d7-8dc6-4ead-acf5-dd78be7782a0

2024-10-03 00:49 UTC, Mythie commented on packages/lib/server-only/pdf/insert-field-in-pdf.ts
> +          : null;
this is a good suggestion

2024-10-03 00:51 UTC, Mythie commented on packages/ui/primitives/document-flow/field-items-advanced-settings/number-field.tsx
> +      </div>
Also a good suggest, we should encode that we want a min/max bounds to the font size e.g. 8-96 within the input/zod schemas and any hardcoded rules

2024-10-03 00:51 UTC, Mythie requested changes
as per prior comments

2024-10-12 07:29 UTC, ephraimduncan commented on packages/lib/types/field-meta.ts
> +  fontSize: z.number().optional(),
Can't do this because other fields such as Checkbox and Radio which uses the`ZBaseFieldMeta ` does not use the fontSize.

2024-10-16 05:05 UTC, Mythie approved these changes

2024-10-16 05:05 UTC, merged