docs: add railway one click deploy
documenso/documenso pull request #242
Opened 2023-08-01 13:51 UTC by dephraiim

2023-08-01 13:57 UTC, ElTimuro requested changes
@dephraiim please a hint that more are coming :)

2023-08-01 14:20 UTC, ElTimuro commented
Nice. I assume this is tested?

2023-08-01 20:14 UTC, dephraiim commented
Yes, two test deployments

https://documenso-web-production-8611.up.railway.app/login
https://documenso-web-production.up.railway.app/dashboard

2023-08-01 23:28 UTC, Mythie approved these changes

2023-08-09 06:22 UTC, Mythie approved these changes

2023-08-09 06:23 UTC, merged