feat: delete draft document
documenso/documenso pull request #491
Opened 2023-10-02 16:35 UTC by G3root

fixes #472

[Screencast 2023-10-02 22:02:59.webm](https://github.com/documenso/documenso/assets/84864519/e224d6c6-239b-4a00-9b53-8598d4408786)

2023-10-06 06:37 UTC, dephraiim requested changes

2023-10-06 06:37 UTC, dephraiim commented on packages/trpc/server/document-router/router.ts
> +    .input(ZGetDocumentByIdQuerySchema)
Can you create a specific schema for the delete router?

2023-10-06 06:37 UTC, dephraiim commented on apps/web/src/app/(dashboard)/documents/data-table-action-dropdown.tsx
> +  const handleDelete = async () => {
Can you rename `handleDelete` to `onDraftDelete` or something instead? 

We always prefer to use the `on<ActionName>` naming convention for event handlers.

2023-10-06 06:38 UTC, dephraiim commented
@G3root  Can you also add a dialog to confirm that you want to delete before? To avoid accidental deletion of documents

2023-10-06 12:10 UTC, G3root commented
@dephraiim pushed some changes

[Screencast 2023-10-06 17:38:24.webm](https://github.com/documenso/documenso/assets/84864519/7176a14d-1124-4839-a008-5446a1b6f75c)

2023-10-09 09:25 UTC, dguyen requested changes

2023-10-09 09:25 UTC, dguyen commented on apps/web/src/app/(dashboard)/documents/data-table-action-dropdown.tsx
> +          <Link href={`/documents/delete/${row.id}`}>
Don't need to create a new page, just directly open the dialog.

2023-10-10 02:55 UTC, merged

2023-10-10 02:56 UTC, dguyen commented
Thanks for adding this feature in @G3root!

/tip 50