feat: enable resend email menu
documenso/documenso pull request #496
Opened 2023-10-03 00:57 UTC by G3root

fixes #473

2023-10-03 07:06 UTC, dguyen commented
Hey @G3root

Sorry about this but we had a spec for this feature which wasn't uploaded as part of the issue. It has now been updated if you could please have a look:

https://github.com/documenso/documenso/issues/473

Thanks for all your contributions so far!

2023-10-03 17:58 UTC, G3root commented
@dguyen pushed some changes


[Screencast 2023-10-03 23:26:15.webm](https://github.com/documenso/documenso/assets/84864519/e772bfcc-b5f2-4049-b763-d46072ee7e8e)

2023-10-05 23:45 UTC, dephraiim commented on packages/lib/server-only/document/send-document.tsx
> +export const sendDocument = async ({ documentId, userId, resendEmails }: SendDocumentOptions) => {
Can you avoid this and instead create a new router for resending a document?

You can also modify the subject of the emails that you send.

2023-10-05 23:45 UTC, dephraiim requested changes

2023-10-05 23:45 UTC, dephraiim commented on packages/lib/server-only/document/send-document.tsx
> +export const sendDocument = async ({ documentId, userId, resendEmails }: SendDocumentOptions) => {
Can you avoid this and instead create a new router for resending a document?

You can also modify the subject of the emails that you send.

2023-10-06 02:51 UTC, G3root commented
@dephraiim pushed some changes

2023-10-06 14:05 UTC, dephraiim requested changes

2023-10-06 14:05 UTC, dephraiim commented on packages/lib/server-only/document/send-document.tsx
> +export type resendDocumentOptions = {
Would prefer `ResendDocumentOptions`

2023-10-06 14:05 UTC, dephraiim commented on packages/lib/server-only/document/send-document.tsx
> +type getSendableDocumentOptions = {
Would prefer `GetSendableDocumentOptions`

2023-10-06 14:05 UTC, dephraiim commented on packages/lib/server-only/document/send-document.tsx
> +async function mailDocuments({ customEmail, document, resendEmails, user }: SendDocumentsOptions) {
`mailDocuments` should not have `SendDocumentsOptions` a prop type

2023-11-15 11:16 UTC, Mythie commented
Guess who's back... it's me here to get this bad boy over the line 🤝🏻

2023-11-15 12:22 UTC, adithyaakrishna commented
based

2023-11-16 01:59 UTC, Mythie approved these changes

2023-11-16 02:05 UTC, merged

2023-11-16 02:06 UTC, Mythie commented
We did it 💪 Thanks Nafees!

![thank-you-stronk](https://github.com/documenso/documenso/assets/13398220/63f72962-8348-433e-a85e-275796aa318b)

2023-11-16 02:32 UTC, G3root commented
> We did it 💪 Thanks Nafees!
> 

![](https://media.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)