Update README.md
documenso/documenso pull request #567
Opened 2023-10-15 10:57 UTC by Shivam250702

Removed Punctuation marks and grammatical error

2023-10-15 10:59 UTC, Mythie commented
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

2023-10-16 13:38 UTC, catalinpit requested changes
Thanks for your changes! Here are some more suggestions if you wish to contribute:

"4. Set the following environement variables." should be "4. Set the following environment variables."

---

"6. Run `npm run dev` root directory to start" should be "6. Run `npm run dev` **in the** root directory to start"

--- 

"To generate your own using these steps and a Linux Terminal or Windows Subsystem for Linux (WSL) see **[Create your own signing certificate](./SIGNING.md)**." should have a comma after `[...] Linux (WSL)`

---

No comma needed here "We support a variety of deployment methods`,` and are actively working on adding more."

---

Comma after the quickstart here "When using the developer quickstart an [Inbucket](https://inbucket.org/) server will be spun up in a docker container that will store all outgoing email locally for you to view."

Also `email` should be `emails`.

---

The sentence "The same can be done when using `npx` for one of bin scripts:" should contains `one of the bins`. The `the` is missing.

---

There should be a comma after `http://localhost:9000` in this sentence "The Web UI can be found at http://localhost:9000 while the SMTP port will be on localhost:2500."

---

Thanks once again!

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +In case you are deploying to a cluster that uses only IPv6,You can use a custom command to pass a parameter to the Next.js start command
"[...] uses only **IPv6,You** can use a custom [...]" should be "[...] uses only **IPv6, you** can use a custom [...]".

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +> Please note the below deployment methods are for v0.9, we will update them to v1.0 once it has been released.
Just a suggestion, but maybe `are for v0.9, **and** we will update` will sound better.

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +Follow these steps to setup documenso on your local machine:
Documenso should be capitalized, I'd say.

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +- Tell us what you think in the [Discussions](https://github.com/documenso/documenso/discussions).
Full stop not needed

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +To run Documenso locally, you will need
Does `Running Documenso locally requires:` sound better? What do you think?

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +We're currently working on a redesign of the application, including a revamp of the codebase, so Documenso can be more intuitive to use and robust to develop upon.
Does `We're currently redesigning the application, including a revamp of the codebase, so Documenso can be more intuitive and robust to use and develop upon.` sound better? What do you think?

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +> **Note**: This is a quickstart for developers. It assumes that you have both [docker](https://docs.docker.com/get-docker/), and [docker-compose](https://docs.docker.com/compose/) installed on your
I don't think the comma is needed here

2023-10-16 13:38 UTC, catalinpit commented on README.md
> +In case you are deploying to a cluster that uses only IPv6,You can use a custom command to pass a parameter to the Next.js start command
There should also be a full stop at the end of the sentence.

2023-10-17 10:42 UTC, catalinpit commented on README.md
> +> **Note**: This is a quickstart for developers. It assumes that you have both [docker](https://docs.docker.com/get-docker/), and [docker-compose](https://docs.docker.com/compose/) installed on your
I checked with Grammarly, and it suggested removing the comma. 👀

2023-10-17 12:23 UTC, catalinpit commented
> please try to merge that part which u think will improve your Doc/Readme

Hey @Shivam250702, sorry, I didn't get it. What should I merge?

2023-10-20 09:43 UTC, closed without merging