Disable the edit and add signer button for completed documents
documenso/documenso pull request #63
Opened 2023-04-09 12:40 UTC by dephraiim

2023-04-10 01:29 UTC, Mythie commented on apps/web/pages/documents/[id]/recipients.tsx
> +                              <></>
This can just be `null`

2023-04-10 01:29 UTC, Mythie commented on apps/web/pages/documents/[id]/recipients.tsx
> +                              <></>
Same for those below

2023-04-10 02:14 UTC, Mythie approved these changes

2023-04-11 13:26 UTC, ElTimuro requested changes
Looks good, just 1 thing: Non availible options should be disabled, not vanished, so the user can learn when sth. is available and when it isn't without being "surprised" something is gone.

2023-04-11 13:32 UTC, ElTimuro approved these changes
Looks good

2023-04-11 13:33 UTC, merged