fix: add conditional rendering of OAuth providers
documenso/documenso pull request #736
Opened 2023-12-06 12:14 UTC by anuragts

Now google OAuth provider is not rendered if client id is not provided
![Screenshot from 2023-12-06 17-39-09](https://github.com/documenso/documenso/assets/79055093/4c427141-0bd0-43c2-a875-121c58f00ed7)

fixes - #735

2023-12-06 12:16 UTC, Mythie commented
Hey there, it looks like you haven't accepted our contributor license agreement yet. In order for us to accept your pull request we ask that you please fill out the CLA:

https://documen.so/cla

2023-12-06 12:18 UTC, anuragts commented
Done !!

2023-12-06 16:53 UTC, dephraiim requested changes

2023-12-06 18:15 UTC, anuragts commented on apps/web/src/components/forms/signin.tsx
> +const shouldRender =
yo Duncan ,
yes I also though of this , will push necessary changes .

2023-12-06 18:38 UTC, anuragts commented on apps/web/src/components/forms/signin.tsx
> +const shouldRender =
Renamed the variable to ALLOW_GOOGLE_OAUTH

2024-01-23 06:06 UTC, dguyen approved these changes
Hey! Apologies for the delay

I've pushed some minor changes since we can't actually access private environment variables on the client side.

Other than that, it's good, thanks a lot for this!

2024-01-23 06:08 UTC, merged