feat: ability to download all the 2FA recovery codes
documenso/documenso pull request #944
Opened 2024-02-16 20:51 UTC by anikdhabal

fixes #938 

https://github.com/documenso/documenso/assets/81948346/8bf807ae-41b0-417b-9f55-d96584e71acb

2024-02-17 07:38 UTC, dephraiim requested changes

2024-02-17 07:38 UTC, dephraiim commented on apps/web/src/components/forms/2fa/view-recovery-codes-dialog.tsx
> +                  <Button>Download</Button>
Can this button be a secondary button?

2024-02-17 07:42 UTC, anikdhabal commented on apps/web/src/components/forms/2fa/view-recovery-codes-dialog.tsx
> +                  <Button>Download</Button>
Yeah, sure.

2024-02-18 21:01 UTC, sachin-duhan reviewed
It's normally recommended to create a utility file that handles Blob / download functionality. Creating or pre-processing file information may not be a part of useEffect.

2024-02-19 10:50 UTC, anikdhabal commented on apps/web/src/components/forms/2fa/view-recovery-codes-dialog.tsx
> +  useEffect(() => {
Thanks for the review. Yeah, it can be a function.

2024-02-21 02:34 UTC, Mythie approved these changes

2024-02-21 02:38 UTC, Mythie commented
LGTM! Thanks for the improvement 🎉

2024-02-21 02:39 UTC, merged

2024-02-21 02:40 UTC, Mythie commented
/tip 200 

Thanks for all your recent PR's while we might be slow to review and address them we do appreciate all the work!

2024-02-21 08:54 UTC, anikdhabal commented
> /tip 200
> 
> Thanks for all your recent PR's while we might be slow to review and address them we do appreciate all the work!

Thank you, Lucas. It means a lot.